### ISSUE TITLE
Можно ветку develop?

### ISSUE THREAD

**Issue by oakymax** [ejen/yii2-fias#4]
Я сделал форк:
- добавил возможность подключения в виде модуля
- сделал возможность указать в настройках модуля базу данных
- добавил PHPDoc и реляции для классов FiasHouse и FiasAddrobj

Еще планирую:
- добавить PHPDoc и реляции во все остальные классы
- переписать миграции так чтобы можно было работать с любой СУБД + генерировать структуру таблиц на основе актуальной XML схемы от ФИАС
- переписать команду импорта (оптимизировать)
- добавить индексы

Ну и еще есть задумки... консольная команда для загрузки обновления, обновление из дельты, тесты.

Стараюсь текущую функциональность не ломать.

Хотелось бы сделать pull request но лучше не в master конечно.

**Comment by alexeevdv** [comment]
Это прекрасно. Помощь была бы кстати. Создал ветку dev
